spring:
  datasource:
    url: jdbc:mysql://10.1.15.225:3307/jpa
    username: root
    password: 1202
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: true
