spring:
  datasource:
    url: jdbc:h2:mem:h2test
    username: root
    password: 1202
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    schema:
      - classpath:sql/staff.sql
    data:
      - classpath:sql/data.sql
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console
